DRIVERS:= \
	objs/driver.o \
	objs/driver_dpf.o \
	objs/driver_drm.o

objs/driver.o: src/driver.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c -o $@ $<;

objs/driver_dpf.o: src/drivers/dpf.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c -o $@ $<;

objs/driver_drm.o: src/drivers/drm.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) $(DRM_INCLUDES) -c -o $@ $<;
